#Tue Oct 14 21:02:48 UTC 2025
micronaut:
  application:
    name: coroutines
  serde:
    deserialization:
      accept-single-value-as-array: true
    naming:
      strategy: SNAKE_CASE

fbi:
  api:
    base-url: https://api.fbi.gov
